import{addDoc,collection,doc,getDoc,limit,onSnapshot,orderBy,query,runTransaction,serverTimestamp,setDoc,updateDoc,where}from'firebase/firestore';import{auth,db}from'./firebase';
export const ADMIN_EMAIL='karank2s6266@gmail.com';
const FALLBACK_RATES={plastic_pet:12,plastic_hdpe:20,plastic_ldpe:10,mixed_plastic:8,cardboard:10,paper:14,newspaper:16,glass:4,metal_aluminium:110,metal_steel:32,metal_iron:28,metal_copper:650,metal_brass:400,ewaste:50,organic:2,textile:8};
const PIECE_WEIGHT_KG={plastic_pet:.025,plastic_hdpe:.05,plastic_ldpe:.01,mixed_plastic:.03,cardboard:.25,paper:.01,newspaper:.15,glass:.3,metal_aluminium:.015,metal_steel:.1,metal_iron:.15,metal_copper:.1,metal_brass:.1,ewaste:.5,organic:.1,textile:.25};
const list=cb=>snap=>cb(snap.docs.map(d=>({id:d.id,...d.data()})));
const currentUid=()=>{const uid=auth.currentUser?.uid;if(!uid)throw Error('Please sign in.');return uid};
const isAdmin=()=>auth.currentUser?.email?.toLowerCase()===ADMIN_EMAIL;
const monthKey=()=>new Date().toISOString().slice(0,7);
const toKg=(value,unit,materialId)=>{const n=Number(value);if(!Number.isFinite(n)||n<=0)throw Error('Quantity must be greater than zero.');if(unit==='g')return n/1000;if(unit==='pieces'){if(!Number.isInteger(n))throw Error('Pieces must be a whole number.');return n*(PIECE_WEIGHT_KG[materialId]||.1)}return n};
export async function completeRegistration({name,role='giver',phone='',address=null}){const u=auth.currentUser;if(!u)throw Error('Please sign in.');const ref=doc(db,'users',u.uid),snap=await getDoc(ref);if(snap.exists())return snap.data();const finalRole=u.email?.toLowerCase()===ADMIN_EMAIL?'admin':role;const profile={uid:u.uid,name:name||u.displayName||'Recycler',email:u.email||'',phone,address,role:finalRole,status:finalRole==='collector'?'pending':'active',createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(ref,profile);return profile}
export async function approveCollector(collectorId){if(!isAdmin())throw Error('Admin access required.');await updateDoc(doc(db,'users',collectorId),{status:'active',approvedBy:currentUid(),approvedAt:serverTimestamp(),updatedAt:serverTimestamp()})}
export async function setMonthlyRate({materialId,ratePerKg,month=monthKey()}){if(!isAdmin())throw Error('Admin access required.');const rate=Number(ratePerKg);if(!materialId||!Number.isFinite(rate)||rate<=0)throw Error('Valid material and rate are required.');const data={materialId,ratePerKg:rate,month,currency:'INR',unit:'kg',setBy:currentUid(),updatedAt:serverTimestamp()};await Promise.all([setDoc(doc(db,'currentRates',materialId),data),setDoc(doc(db,'monthlyRates',month,'items',materialId),data)]);return data}
export async function createPickupRequest(data){const uid=currentUid(),materialId=String(data.materialId||''),unit=data.originalUnit||'kg',originalQuantity=Number(data.originalQuantity??data.estimatedKg),estimatedKg=toKg(originalQuantity,unit,materialId),rateSnap=await getDoc(doc(db,'currentRates',materialId)),adminRate=rateSnap.exists()?Number(rateSnap.data().ratePerKg||0):0,ratePerKg=adminRate>0?adminRate:(FALLBACK_RATES[materialId]||5),rateSource=adminRate>0?'admin':'average_fallback',estimatedValue=Number((estimatedKg*ratePerKg).toFixed(2));const ref=await addDoc(collection(db,'pickupRequests'),{giverId:uid,collectorId:data.collectorId||null,collectorName:data.collectorName||null,materialId,originalQuantity,originalUnit:unit,estimatedKg,pieceWeightKg:unit==='pieces'?(PIECE_WEIGHT_KG[materialId]||.1):null,ratePerKg,rateSource,estimatedValue,imageId:data.imageId||null,address:data.address||null,giverLocation:data.location||null,status:data.collectorId?'requested':'open',timeline:[{status:'requested',at:new Date().toISOString(),by:uid}],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return{id:ref.id,estimatedKg,ratePerKg,rateSource,estimatedValue}}
export async function acceptPickup(pickupId){const uid=currentUid(),profile=await getDoc(doc(db,'users',uid));if(profile.data()?.role!=='collector'||profile.data()?.status!=='active')throw Error('Approved collector access required.');await runTransaction(db,async tx=>{const ref=doc(db,'pickupRequests',pickupId),snap=await tx.get(ref);if(!snap.exists())throw Error('Pickup not found.');const p=snap.data();if(!['open','requested'].includes(p.status))throw Error('Pickup is no longer available.');if(p.collectorId&&p.collectorId!==uid)throw Error('Assigned to another collector.');tx.update(ref,{collectorId:uid,status:'accepted',timeline:[...(p.timeline||[]),{status:'accepted',at:new Date().toISOString(),by:uid}],updatedAt:serverTimestamp()})})}
export async function updatePickupStatus(pickupId,status){if(!['on_the_way','arrived'].includes(status))throw Error('Invalid status.');const uid=currentUid(),ref=doc(db,'pickupRequests',pickupId),snap=await getDoc(ref);if(!snap.exists()||snap.data().collectorId!==uid)throw Error('Pickup is not assigned to you.');await updateDoc(ref,{status,timeline:[...(snap.data().timeline||[]),{status,at:new Date().toISOString(),by:uid}],updatedAt:serverTimestamp()})}
export async function completePickup(pickupId,finalKg){const collectorId=currentUid(),kg=Number(finalKg);if(!Number.isFinite(kg)||kg<=0)throw Error('Verified weight must be positive.');let result;await runTransaction(db,async tx=>{const pRef=doc(db,'pickupRequests',pickupId),pSnap=await tx.get(pRef);if(!pSnap.exists())throw Error('Pickup not found.');const p=pSnap.data();if(p.collectorId!==collectorId||p.status==='completed')throw Error('Cannot complete this pickup.');const amount=Number((kg*Number(p.ratePerKg)).toFixed(2)),transactionRef=doc(collection(db,'transactions')),notificationRef=doc(collection(db,'notifications'));tx.update(pRef,{status:'completed',finalKg:kg,finalAmount:amount,completedAt:serverTimestamp(),timeline:[...(p.timeline||[]),{status:'completed',at:new Date().toISOString(),by:collectorId}],updatedAt:serverTimestamp()});tx.set(transactionRef,{pickupId,giverId:p.giverId,collectorId,materialId:p.materialId,originalQuantity:p.originalQuantity,originalUnit:p.originalUnit||'kg',weightKg:kg,ratePerKg:p.ratePerKg,rateSource:p.rateSource,amount,type:'pickup_credit',createdAt:serverTimestamp()});tx.set(notificationRef,{userId:p.giverId,pickupId,title:'Pickup completed',body:`₹${amount.toFixed(0)} was credited for the pickup.`,read:false,createdAt:serverTimestamp()});result={finalKg:kg,finalAmount:amount}});return result}
export async function saveCollectorDetails(uid,details){if(uid!==currentUid())throw Error('Not allowed.');const data={businessName:details.businessName.trim(),ownerName:details.ownerName.trim(),phone:details.phone.trim(),addressLine:details.addressLine.trim(),city:details.city.trim(),state:details.state.trim(),postalCode:details.postalCode.trim(),serviceRadiusKm:Number(details.serviceRadiusKm||10),acceptedMaterials:details.acceptedMaterials||[],location:{latitude:Number(details.location.latitude),longitude:Number(details.location.longitude),accuracy:details.location.accuracy||null},detailsCompleted:true,locationUpdatedAt:serverTimestamp(),updatedAt:serverTimestamp()};await updateDoc(doc(db,'users',uid),data);await setDoc(doc(db,'collectorLocations',uid),{collectorId:uid,businessName:data.businessName,...data.location,serviceRadiusKm:data.serviceRadiusKm,active:true,updatedAt:serverTimestamp()},{merge:true});return data}
export const watchProfile=(uid,cb,error)=>onSnapshot(doc(db,'users',uid),s=>cb(s.exists()?s.data():null),error);
export const watchCurrentRates=(cb,error)=>onSnapshot(collection(db,'currentRates'),list(cb),error);
export const watchApprovedCollectors=(cb,error)=>onSnapshot(query(collection(db,'users'),where('role','==','collector'),where('status','==','active'),limit(50)),list(cb),error);
export const watchGiverPickups=(uid,cb,error)=>onSnapshot(query(collection(db,'pickupRequests'),where('giverId','==',uid),orderBy('createdAt','desc'),limit(50)),list(cb),error);
export const watchCollectorPickups=(uid,cb,error)=>onSnapshot(query(collection(db,'pickupRequests'),where('collectorId','==',uid),orderBy('createdAt','desc'),limit(50)),list(cb),error);
export const watchOpenPickups=(cb,error)=>onSnapshot(query(collection(db,'pickupRequests'),where('status','==','open'),orderBy('createdAt','desc'),limit(50)),list(cb),error);
export const watchTransactions=(uid,cb,error)=>onSnapshot(query(collection(db,'transactions'),where('giverId','==',uid),orderBy('createdAt','desc'),limit(50)),list(cb),error);
export const watchNotifications=(uid,cb,error)=>onSnapshot(query(collection(db,'notifications'),where('userId','==',uid),orderBy('createdAt','desc'),limit(50)),list(cb),error);
export const watchPendingCollectors=(cb,error)=>{if(!isAdmin())return()=>{};return onSnapshot(query(collection(db,'users'),where('role','==','collector'),where('status','==','pending'),limit(50)),list(cb),error)};
export function distanceKm(a,b){if(!Number.isFinite(Number(a?.latitude))||!Number.isFinite(Number(b?.latitude)))return null;const rad=n=>n*Math.PI/180,R=6371,dLat=rad(Number(b.latitude)-Number(a.latitude)),dLng=rad(Number(b.longitude)-Number(a.longitude)),x=Math.sin(dLat/2)**2+Math.cos(rad(Number(a.latitude)))*Math.cos(rad(Number(b.latitude)))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
