import React from 'react';
import {Text,TouchableOpacity,View,StyleSheet} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {C} from '../theme';
export function Btn({title,onPress,outline=false,disabled=false,icon}){return <TouchableOpacity onPress={onPress} disabled={disabled} style={[s.btn,outline&&s.outline,disabled&&{opacity:.45}]}>{icon&&<Ionicons name={icon} size={18} color={outline?C.green:C.bg}/>}<Text style={[s.btnText,outline&&{color:C.text}]}>{title}</Text></TouchableOpacity>}
export function Header({title,back,right}){return <View style={s.header}><View style={{width:36}}>{back&&<TouchableOpacity onPress={back}><Ionicons name="chevron-back" size={26} color={C.text}/></TouchableOpacity>}</View><Text style={s.headerTitle}>{title}</Text><View style={{width:36}}>{right}</View></View>}
export function Card({children,style}){return <View style={[s.card,style]}>{children}</View>}
export function Pill({text,solid=false}){return <View style={[s.pill,solid&&s.pillSolid]}><Text style={[s.pillText,solid&&{color:'#fff'}]}>{text}</Text></View>}
export function Row({icon,title,value,onPress,danger}){return <TouchableOpacity style={s.row} onPress={onPress}><Ionicons name={icon} size={20} color={danger?C.red:'#173a31'}/><Text style={[s.rowTitle,danger&&{color:C.red}]}>{title}</Text>{value?<Text style={s.rowValue}>{value}</Text>:<Ionicons name="chevron-forward" size={18} color={C.muted}/>}</TouchableOpacity>}
export const ui=s;
const s=StyleSheet.create({btn:{height:50,borderRadius:11,backgroundColor:C.green,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,paddingHorizontal:16},outline:{backgroundColor:'transparent',borderWidth:1,borderColor:C.line},btnText:{fontWeight:'800',color:C.bg},header:{height:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headerTitle:{fontSize:17,fontWeight:'700',color:C.text},card:{backgroundColor:'#f7fbfa',borderRadius:14,padding:15,marginBottom:10},pill:{backgroundColor:'#d9f8e3',borderRadius:7,paddingHorizontal:8,paddingVertical:4,alignSelf:'flex-start'},pillSolid:{backgroundColor:'#12ad59'},pillText:{fontSize:10,color:'#148148',fontWeight:'700'},row:{height:53,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#dfe9e7'},rowTitle:{flex:1,color:'#16382f',fontWeight:'600'},rowValue:{color:'#4d7169',fontSize:12}});
